// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// annealing
double annealing(NumericMatrix Corr, NumericVector S);
RcppExport SEXP Morphometrics_annealing(SEXP CorrSEXP, SEXP SSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type Corr(CorrSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type S(SSEXP );
        double __result = annealing(Corr, S);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// createRandomMatrix
Eigen::MatrixXd createRandomMatrix(int dimension, float ke);
RcppExport SEXP Morphometrics_createRandomMatrix(SEXP dimensionSEXP, SEXP keSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type dimension(dimensionSEXP );
        Rcpp::traits::input_parameter< float >::type ke(keSEXP );
        Eigen::MatrixXd __result = createRandomMatrix(dimension, ke);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
