// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// annealing
double annealing(NumericMatrix Corr, NumericVector S);
RcppExport SEXP evolqg_annealing(SEXP CorrSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type Corr(CorrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type S(SSEXP);
    __result = Rcpp::wrap(annealing(Corr, S));
    return __result;
END_RCPP
}
