# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RS <- function(x, y, num_vectors) {
    .Call('evolqg_RS', PACKAGE = 'evolqg', x, y, num_vectors)
}

annealing <- function(Corr, S) {
    .Call('evolqg_annealing', PACKAGE = 'evolqg', Corr, S)
}

