# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RS <- function(x, y, num_vectors) {
    .Call('_evolqg_RS', PACKAGE = 'evolqg', x, y, num_vectors)
}

delta_z_corr <- function(x, y, num_vectors, random_vectors) {
    .Call('_evolqg_delta_z_corr', PACKAGE = 'evolqg', x, y, num_vectors, random_vectors)
}

